spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8083

microservices:
  customer:
    urlPaths:
      getCustomerById: http://localhost:8081/api/customers/{customerId}
      putCustomer: http://localhost:8081/api/customers/{customerId}
  product:
    urlPaths:
      getProductByType: http://localhost:8082/api/product
  credit:
    urlPaths:
      getCreditsByCustomerId: http://localhost:8085/api/credits
  creditCards:
    urlPaths:
      getCreditCardsByCustomerId: http://localhost:8086/api/creditCards
