spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8083

microservices:
  customer:
    urlPaths:
      getCustomerById: http://localhost:8081/api/customers/{customerId}
      putCustomer: http://localhost:8081/api/customers/{customerId}
  creditCards:
    urlPaths:
      getCreditCardsByCustomerId: http://localhost:8086/api/creditCards