spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8083

microservices:
  customer:
    urlPaths:
      getCustomer: http://localhost:8081/api/customers
      putCustomer: http://localhost:8081/api/customers/{customerId}
  creditCards:
    urlPaths:
      getCreditCards: http://localhost:8086/api/creditCards
  products:
    urlPaths:
      getProducts: http://localhost:8086/api/products