spring:
  application:
    name: account
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8082

microservices:
  customer:
    urlPaths:
      getCustomerById: http://localhost:8081/api/customers/{customerId}
      putCustomer: http://localhost:8081/api/customers/{customerId}
  credit:
    urlPaths:
      getCreditsByCustomerId: http://localhost:8083/api/credits